from travelpost.writers.pdf.libs.reportlab.platypus import Paragraph

class Default(Paragraph): ...
class Body(Paragraph): ...
class P(Paragraph): ...
class B(Paragraph): ...
class It(Paragraph): ...
class Subtitle(Paragraph): ...
class Title(Paragraph): ...
class H1(Paragraph): ...
class H2(Paragraph): ...
class H3(Paragraph): ...
