from travelpost.writers.pdf.libs.reportlab.platypus import Paragraph

class B(Paragraph): ...
class Body(Paragraph): ...
class Default(Paragraph): ...
class H1(Paragraph): ...
class H2(Paragraph): ...
class H3(Paragraph): ...
class It(Paragraph): ...
class P(Paragraph): ...
class PostStatsHeader(Paragraph): ...
class PostStatsMain(Paragraph): ...
class Subtitle(Paragraph): ...
class SummaryBody(Paragraph): ...
class SummaryHeading2(Paragraph): ...
class SummaryStatsFooter(Paragraph): ...
class SummaryStatsMain(Paragraph): ...
class Title(Paragraph): ...
